root = "."
tmp_dir = "tmp"
testdata_dir = "testdata"

[build]
cmd = "go build -o ./tmp/onyxhub-backend.exe ./cmd/server"
entrypoint = ["./tmp/onyxhub-backend.exe"]
include_ext = ["go"]
exclude_dir = ["tmp", "data", "vendor"]
exclude_regex = ["_test.go"]
delay = 1000
stop_on_error = true
send_interrupt = true
kill_delay = "500ms"

[log]
time = true

[color]
build = "yellow"
runner = "green"
watcher = "cyan"

[screen]
clear_on_rebuild = false
keep_scroll = true

[misc]
clean_on_exit = false
